RadioSolution\StaticContentBundle\Entity\CategoryStaticContent:
  type: entity
  table: static_content__category
  id:
    id:
      type: integer
      generator: { strategy: AUTO }
  fields:
    name:
      type: string
      length: 100
    body:
      type: string
      nullable: true
    slug:
      type: string
  OneToMany:
    staticContent:
      targetEntity: StaticContent
      mappedBy: categoryStaticContent
  oneToOne:
    image:
      nullable: true
      targetEntity: Application\Sonata\MediaBundle\Entity\Media
      joinColumn:
        name: id_image
        referencedColumnName: id
  manyToOne:
    parent:
      nullable: true
      default: NULL
      targetEntity: CategoryStaticContent
      joinColumn:
        name: id_parent
        referencedColumnName: id