RadioSolution\StaticContentBundle\Entity\StaticContent:
  type: entity
  table: static_content
  id:
    id:
      type: integer
      generator: { strategy: AUTO }
  fields:
    title:
      type: string
      length: 100
    name:
      type: string
      length: 100
    introduction:
      type: string
      length: 255
    body:
      type: string
    date_add:
      type: date 
  oneToOne:
    image:
      targetEntity: Application\Sonata\MediaBundle\Entity\Media
      joinColumn:
        name: id_image
        referencedColumnName: id
  manyToOne:
    CategoryStaticContent:
      targetEntity: CategoryStaticContent
      inversedBy: StaticContent
      joinColumn:
          name: id_category
          referencedColumnName: id