RadioSolution\StaticContentBundle\Entity\StaticContent:
  type: entity
  table: static_content
  id:
    id:
      type: integer
      generator: { strategy: AUTO }
  fields:
    title:
      type: string
      length: 100
    name:
      type: string
      length: 100
    introduction:
      type: string
      length: 255
    body:
      type: string
  manyToOne:
    CategoryStaticContent:
      targetEntity: CategoryStaticContent
      inversedBy: StaticContent
      joinColumn:
          name: id_category
          referencedColumnName: id