RadioSolution\ProgramBundle\Entity\Emission:
  type: entity
  table: program__emission
  id:
    id:
      type: integer
      generator: { strategy: AUTO }
  fields:
    name:
      type: string
      length: 100
    description:
      type: string
    diffusion_start:
      type: date
    difusion_stop:
      type: date
  manyToOne:
    theme:
      targetEntity: EmissionTheme
      joinColumn:
        name: id_theme
        referencedColumnName: id
    group:
      targetEntity: Application\Sonata\UserBundle\Entity\Group
      joinColumn:
        name: id_group
        referencedColumnName: id
    media:
      targetEntity: Application\Sonata\MediaBundle\Entity\Media
      joinColumn:
        name: id_media
        referencedColumnName: id
  oneToMany:
    ExceptionalBroadcast:
      targetEntity: ExceptionalBroadcast
      cascade: [all]
      mappedBy: Emission
    WeeklyBroadcast:
      targetEntity: WeeklyBroadcast
      cascade: [all]
      mappedBy: Emission