imports:
    - { resource: parameters.ini }
    - { resource: config_sr.yml }
    - { resource: security.yml }
    - { resource: config_knp.yml }
    - { resource: config_fos.yml }
    - { resource: config_sonata.yml }
<<<<<<< HEAD
    - { resource: config_euradio.yml }
    - { resource: config_other.yml }
    
framework:
#    esi:             ~
    translator:      { fallback: %locale% }
    secret:          %secret%
=======
    - { resource: config_other.yml }
    - { resource: "@ContactBundle/Resources/config/config.yml" }
    
framework:
#    esi:             ~
    translator:      { fallback: "%locale%" }
    secret:          "%secret%"
>>>>>>> master
    charset:         UTF-8
    router:          { resource: "%kernel.root_dir%/config/routing.yml" }
    form:            true
    csrf_protection: true
    validation:      { enable_annotations: true }
    templating:      { engines: ['twig'] } #assets_version: SomeVersionScheme
    session:
        default_locale: "%locale%"
        auto_start:     true

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"

# Assetic Configuration
assetic:
    debug:          "%kernel.debug%"
    use_controller: false
    # java: /usr/bin/java
    filters:
#        yui_css:
#            jar: "%kernel.root_dir%/Resources/java/yuicompressor.jar"
#        yui_js:
#            jar: "%kernel.root_dir%/Resources/java/yuicompressor.jar"
        cssrewrite: ~
        # closure:
        #     jar: %kernel.root_dir%/java/compiler.jar
        # yui_css:
        #     jar: %kernel.root_dir%/java/yuicompressor-2.4.2.jar

# Doctrine Configuration
doctrine:
    dbal:
        driver:   "%database_driver%"
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
        types:
            json: Sonata\Doctrine\Types\JsonType

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: gmail
    username:  "%mailer_user%"
    password:  "%mailer_password%"

jms_security_extra:
    secure_controllers:  true
    secure_all_services: false
