fos_user:
    db_driver: orm
    firewall_name: main
    user_class: Application\Sonata\UserBundle\Entity\User
    group:
        group_class: Application\Sonata\UserBundle\Entity\Group
        
fos_facebook:
  file:   %kernel.root_dir%/../vendor/facebook/src/base_facebook.php
  alias:  facebook
  app_id: 123456879
  secret: s3cr3t
  cookie: true
  permissions: [email, user_birthday, user_location]

fos_comment:
  db_driver: orm
  class:
      model:
          comment: MyProject\MyBundle\Entity\Comment
          thread: MyProject\MyBundle\Entity\Thread
               
#fos_twitter:
#        file: %kernel.root_dir%/../vendor/twitteroauth/twitteroauth/twitteroauth.php
#        consumer_key:  LAWjBJqSf23NZj8kw488Q
#        consumer_secret:    T69KoJdyyhvETgiNUqux1cQQFLi07pXvVlreSWw
#        callback_url: http://www.example.com/login_check
      
