parameters:
#    carrousel.example.class: RadioSolution\CarrouselBundle\Example

services:
#    carrousel.example:
#        class: %carrousel.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
