RadioSolution\PodcastBundle\Entity\Podcast:
  type: entity
  table: podcast__podcast
  id:
    id:
      type: integer
      generator: { strategy: AUTO }
  fields:
    name:
      type: string
      length: 100
    real_time_start:
      type: datetime
  oneToOne:
    filePodcast:
      targetEntity: Application\Sonata\MediaBundle\Entity\Media
      joinColumn:
        name: id_media_podcast
        referencedColumnName: id
    post:
      targetEntity: Application\Sonata\NewsBundle\Entity\Post
      inversedBy: RadioSolution\PodcastBundle\Entity\Podcast
      joinColumn:
        name: podcast_id
        referencedColumnName: id