PodcastBundle_homepage:
    pattern:  /podcast
    defaults: { _controller: PodcastBundle:Podcast:index }
PodcastBundle_homepage:
    pattern:  /podcast_show{id}
    defaults: { _controller: PodcastBundle:Podcast:show }