PodcastBundle_homepage:
    pattern:  /podcasts
    defaults: { _controller: "PodcastBundle:Podcast:index" }
PodcastBundle_show:
    pattern:  /podcast/{id}
    defaults: { _controller: "PodcastBundle:Podcast:show" }
PodcastBundle_date:
    pattern:  /podcasts-date/{date}
    defaults: { _controller: "PodcastBundle:Podcast:indexDate" }