parameters:
#    podcast.example.class: RadioSolution\PodcastBundle\Example

services:
#    podcast.example:
#        class: %podcast.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
