parameters:
#    program.example.class: RadioSolution\ProgramBundle\Example

services:
#    program.example:
#        class: %program.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]