RadioSolution\MenuBundle\Entity\Menu:
  type: entity
  table: menu__menu
  id:
    id:
      type: integer
      generator: { strategy: AUTO }
  fields:
    name:
      type: string
      length: 100
  oneToMany:
    links:
      null: true
      targetEntity: Item
      mappedBy: id_menu