RadioSolution\MenuBundle\Entity\SubMenu:
  type: entity
  table: menu__submenu
  id:
    id:
      type: integer
      generator: { strategy: AUTO }
  fields:
    name:
      type: string
      length: 100
  oneToMany:
    links:
      targetEntity: Link
      mappedBy: menu